name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test --if-present

      - id: build
        name: Build production bundle
        run: npm run build --if-present

      - name: Zip build folder (if present)
        run: |
          if [ -d build ]; then
            zip -r build-${{ github.ref_name }}.zip build;
          else
            echo "No build directory found, skipping zip.";
          fi

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Automated release created from commit ${{ github.sha }} by GitHub Actions.
          draft: false
          prerelease: false

      - name: Upload build zip to release
        if: steps.create_release.outputs.upload_url != '' && (exists("build-${{ github.ref_name }}.zip") || always())
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build-${{ github.ref_name }}.zip
          asset_name: build-${{ github.ref_name }}.zip
          asset_content_type: application/zip
